### ISSUE TITLE
Invalid schema content: (host.$_root.alternatives)

### ISSUE THREAD

**Issue by Domiserver** [nestjsplus/knex-cats#4]
Hi John,

I hope you are well in the middle of this global issue.

Thanks so much for this repo and the two powerful articles related:
(https://dev.to/nestjs/advanced-nestjs-how-to-build-completely-dynamic-nestjs-modules-1370)
(https://dev.to/nestjs/build-a-nestjs-module-for-knex-js-or-other-resource-based-libraries-in-5-minutes-12an)

I've been using TypeORM with NestJS but due to drop columns, numeric and synchronization issues, I decided to switch to Knex.

After setting up the dynamic knex module, I'm getting the following error when I use the command # npm run start:dev

```
4:30:02 PM] Found 0 errors. Watching for file changes.
[Nest] 3650   - 03/25/2020, 4:30:12 PM   [NestFactory] Starting Nest application...
[Nest] 3650   - 03/25/2020, 4:30:12 PM   [InstanceLoader] ConfigManagerModule dependencies initialized +87ms
[Nest] 3650   - 03/25/2020, 4:30:12 PM   [InstanceLoader] ApiModule dependencies initialized +3ms
[Nest] 3650   - 03/25/2020, 4:30:12 PM   [InstanceLoader] ProductModule dependencies initialized +11ms
[Nest] 3650   - 03/25/2020, 4:30:12 PM   [ExceptionHandler] Invalid schema content: (host.$_root.alternatives)
```

I created in PostgreSQL the database, ran the "create.sql" sample code and set up the development.env with the right credentials. 

PostgreSQL v12.2
"@hapi/joi": "^17.1.1",
"@nestjs/core": "^7.0.4",
"@nestjsplus/config": "^1.0.14",
"@nestjsplus/knex": "^1.0.0",
"@nestjsplus/massive": "^1.2.0",

Have you encounter this "Invalid Schema Content" error?

Thanks again for sharing some of your knowledge about NestJS development.
Ron

**Comment by johnbiundo** [comment]
@Domiserver Thanks for the kind thoughts.

TBH, I haven't worked with this library in quite a while.  Do you happen to have a small repo that reproduces the problem?  Also, I don't think there should be any Nest v7 compatibility issues, but I haven't tried with v7. Which are you using?

**Comment by Domiserver** [comment]
Good morning @johnbiundo , 

I went back to your previous article, and applied carefully every step.
https://dev.to/nestjs/build-a-nestjs-module-for-knex-js-or-other-resource-based-libraries-in-5-minutes-12an

Knex ran successfully in my project.  I tested Knex CRUD against PostgreSQL and all operations are working well with the database. 

My final step is to add Objection.js. 
So far I have added two dynamic modules (knex and objection) to my existing Nest project.
Which route would you suggest I take?  

Thanks so much for sharing your thoughts.

**Comment by johnbiundo** [comment]
@Domiserver Great to hear it!  Unfortunately I haven't worked with Objection.  I'd be glad to take a look at a project if you have something to share.

**Comment by Domiserver** [comment]
@johnbiundo  

I decided to set up PostgreSQL with Objection.js with Knex.js.  This set up is working properly.

Thanks again for taking time away from your activities to respond about my issue.
Regards,
Ron
